name: check
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.15.0-178.0.dev <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  firebase_core: ^1.8.0

  cloud_firestore: ^2.5.4

  firebase_database: ^8.0.1

  firebase_storage: ^10.0.6

  rounded_loading_button: ^2.0.9

  provider: ^6.0.1

  intl: ^0.17.0

  image_picker: ^0.8.4+3

  image: ^3.0.8

  path_provider: ^2.0.6

  uuid: ^3.0.5

  app_settings: ^4.1.1

  connectivity: ^3.0.6

  flutter_animated_dialog: ^2.0.1


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:

  uses-material-design: true
